server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shafhaz/spring-cloud-config-store
          search-paths:
            - 'service-config/*service'
          #username:
          #passphrase:
